import { Bell, FileBarChart, History, Layers3, Map, Plus, Search, Settings, Upload, UserRound, Users } from "lucide-react";
import { MapCanvas } from "@/components/map/MapCanvas";
import { PlotDetails } from "../PlotDetails";
import { PlotList } from "../PlotList";
import { LayersPanel, ProfilePanel, ReportsPanel, SettingsPanel, UsersPanel } from "../WorkspacePanels";
import type { WorkspaceSection, WorkspaceViewProps } from "../types";
import { AuditPanel } from "../AuditPanel";

const nav: { id: WorkspaceSection; label: string; icon: React.ReactNode }[] = [
  { id: "map", label: "Карта", icon: <Map size={21} /> }, { id: "layers", label: "Шари", icon: <Layers3 size={21} /> }, { id: "reports", label: "Звіти", icon: <FileBarChart size={21} /> }, { id: "history", label: "Журнал", icon: <History size={21} /> }, { id: "users", label: "Користувачі", icon: <Users size={21} /> },
];

export function DesktopWorkspace(props: WorkspaceViewProps) {
  const initials = props.user.name.split(/\s+/).slice(0, 2).map((word) => word[0]).join("").toLocaleUpperCase("uk") || "GP";
  const isAdmin = props.user.role === "admin";
  return <main className="desktop-shell" data-workspace={props.workspace}>
    <header className="desktop-topbar"><div className="brand-lockup"><span className="brand-mark">GP</span><strong>GeoPartners</strong></div>{props.preview ? <div className="desktop-topbar__status"><span />Демо-дані</div> : props.testWorkspaceEnabled ? <label className="workspace-switch" data-workspace={props.workspace}><span /><select aria-label="База даних" value={props.workspace} onChange={(event) => void props.actions.setWorkspace(event.target.value as "production" | "sandbox")}><option value="production">Робоча база</option><option value="sandbox">Тестова база</option></select></label> : <span />}<div className="desktop-topbar__actions"><button className="icon-button" type="button" onClick={props.actions.openNotifications} title="Сповіщення" aria-label="Сповіщення"><Bell size={19} /></button><button className="avatar-button" type="button" onClick={() => props.actions.setSection("profile")} title="Профіль" aria-label="Профіль">{initials}</button></div></header>
    <nav className="desktop-rail" aria-label="Основна навігація">{nav.filter((item) => item.id !== "users" || isAdmin).map((item) => <button className="rail-button" data-active={props.activeSection === item.id} key={item.id} type="button" onClick={() => props.actions.setSection(item.id)} title={item.label} aria-label={item.label}>{item.icon}</button>)}<span className="desktop-rail__spacer" /><button className="rail-button" data-active={props.activeSection === "settings"} type="button" onClick={() => props.actions.setSection("settings")} title="Налаштування" aria-label="Налаштування"><Settings size={21} /></button></nav>
    {props.activeSection === "map" ? <>
      <aside className="desktop-sidebar"><div className="section-heading"><div><span className="eyebrow">Робочий набір</span><h1>Земельні ділянки</h1></div><button className="icon-button icon-button--accent" type="button" onClick={props.actions.openAdd} title="Додати ділянку" aria-label="Додати ділянку"><Plus size={20} /></button></div><label className="search-field"><Search size={18} aria-hidden="true" /><input value={props.query} onChange={(event) => props.actions.setQuery(event.target.value)} placeholder="Номер, власник або орендар" /></label><div className="list-toolbar"><span>{props.plots.length} ділянки</span>{isAdmin ? <button type="button" onClick={props.actions.openImport}><Upload size={16} />Імпорт</button> : null}</div><PlotList plots={props.plots} selectedId={props.selectedId} onSelect={props.actions.select} categories={props.categories} /></aside>
      <section className="desktop-map" aria-label="Карта ділянок"><MapCanvas plots={props.plots} categories={props.categories} baseMap={props.baseMap} selectedId={props.selectedId} onSelect={props.actions.select} /></section>
      <aside className="desktop-details"><PlotDetails plot={props.selectedPlot} categories={props.categories} onEdit={props.actions.openEdit} onDocuments={props.actions.openDocuments} onOpenCard={props.actions.openCard} /><div className="desktop-user-note"><UserRound size={18} /><span>Зміни зберігаються у спільній робочій базі.</span></div></aside>
    </> : <div className="desktop-page">{props.activeSection === "layers" ? <LayersPanel categories={props.categories} baseMap={props.baseMap} actions={props.actions} canManage={isAdmin} /> : null}{props.activeSection === "reports" ? <ReportsPanel plots={props.plots} categories={props.categories} actions={props.actions} /> : null}{props.activeSection === "history" ? <AuditPanel preview={props.preview} baseMap={props.baseMap} canRestore={isAdmin} onRestore={props.actions.restoreAuditEntry} workspace={props.workspace} /> : null}{props.activeSection === "users" ? <UsersPanel isAdmin={isAdmin} /> : null}{props.activeSection === "settings" ? <SettingsPanel actions={props.actions} canImport={isAdmin} workspace={props.workspace} testWorkspaceEnabled={props.testWorkspaceEnabled} canManageWorkspaces={isAdmin} /> : null}{props.activeSection === "profile" ? <ProfilePanel user={props.user} googleEnabled={props.googleEnabled} preview={props.preview} workspace={props.workspace} testWorkspaceEnabled={props.testWorkspaceEnabled} actions={props.actions} /> : null}</div>}
  </main>;
}
