import { Bell, FileBarChart, History, Layers3, Map, Plus, Search, Settings, Upload, UserRound, Users } from "lucide-react";
import { useTranslations } from "next-intl";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { MapCanvas } from "@/components/map/MapCanvas";
import { PlotDetails } from "../PlotDetails";
import { PlotList } from "../PlotList";
import { LayersPanel, ProfilePanel, ReportsPanel, SettingsPanel, UsersPanel } from "../WorkspacePanels";
import type { WorkspaceSection, WorkspaceViewProps } from "../types";
import { AuditPanel } from "../AuditPanel";

const nav: { id: WorkspaceSection; labelKey: "map" | "layers" | "reports" | "history" | "users"; icon: React.ReactNode }[] = [
  { id: "map", labelKey: "map", icon: <Map size={21} /> }, { id: "layers", labelKey: "layers", icon: <Layers3 size={21} /> }, { id: "reports", labelKey: "reports", icon: <FileBarChart size={21} /> }, { id: "history", labelKey: "history", icon: <History size={21} /> }, { id: "users", labelKey: "users", icon: <Users size={21} /> },
];

export function DesktopWorkspace(props: WorkspaceViewProps) {
  const t = useTranslations("workspace");
  const initials = props.user.name.split(/\s+/).slice(0, 2).map((word) => word[0]).join("").toLocaleUpperCase() || "GP";
  const isAdmin = props.user.role === "admin";
  return <main className="desktop-shell" data-workspace={props.workspace}>
    <header className="desktop-topbar"><div className="brand-lockup"><span className="brand-mark">GP</span><strong>GeoPartners</strong></div>{props.preview ? <div className="desktop-topbar__status"><span />{t("demoData")}</div> : props.testWorkspaceEnabled ? <label className="workspace-switch" data-workspace={props.workspace}><span /><select aria-label={t("database")} value={props.workspace} onChange={(event) => void props.actions.setWorkspace(event.target.value as "production" | "sandbox")}><option value="production">{t("productionDatabase")}</option><option value="sandbox">{t("testDatabase")}</option></select></label> : <span />}<div className="desktop-topbar__actions"><LanguageSwitcher compact /><button className="icon-button" type="button" onClick={props.actions.openNotifications} title={t("notifications")} aria-label={t("notifications")}><Bell size={19} /></button><button className="avatar-button" type="button" onClick={() => props.actions.setSection("profile")} title={t("profile")} aria-label={t("profile")}>{initials}</button></div></header>
    <nav className="desktop-rail" aria-label={t("mainNavigation")}>{nav.filter((item) => item.id !== "users" || isAdmin).map((item) => { const label = t(item.labelKey); return <button className="rail-button" data-active={props.activeSection === item.id} key={item.id} type="button" onClick={() => props.actions.setSection(item.id)} title={label} aria-label={label}>{item.icon}</button>; })}<span className="desktop-rail__spacer" /><button className="rail-button" data-active={props.activeSection === "settings"} type="button" onClick={() => props.actions.setSection("settings")} title={t("settings")} aria-label={t("settings")}><Settings size={21} /></button></nav>
    {props.activeSection === "map" ? <>
      <aside className="desktop-sidebar"><div className="section-heading"><div><span className="eyebrow">{t("workingSet")}</span><h1>{t("landPlots")}</h1></div>{props.canEditPlots ? <button className="icon-button icon-button--accent" type="button" onClick={props.actions.openAdd} title={t("addPlot")} aria-label={t("addPlot")}><Plus size={20} /></button> : null}</div><label className="search-field"><Search size={18} aria-hidden="true" /><input value={props.query} onChange={(event) => props.actions.setQuery(event.target.value)} placeholder={t("searchPlaceholder")} /></label><div className="list-toolbar"><span>{t("plotCount", { count: props.plots.length })}</span>{isAdmin ? <button type="button" onClick={props.actions.openImport}><Upload size={16} />{t("import")}</button> : null}</div><PlotList plots={props.plots} selectedId={props.selectedId} onSelect={props.actions.select} categories={props.categories} /></aside>
      <section className="desktop-map" aria-label={t("plotMap")}><MapCanvas plots={props.plots} categories={props.categories} baseMap={props.baseMap} selectedId={props.selectedId} onSelect={props.actions.select} /></section>
      <aside className="desktop-details"><PlotDetails plot={props.selectedPlot} categories={props.categories} plotStatuses={props.plotStatuses} onEdit={props.canEditPlots ? props.actions.openEdit : undefined} onOpenStages={props.actions.openStages} onDocuments={props.actions.openDocuments} onOpenCard={props.actions.openCard} /><div className="desktop-user-note"><UserRound size={18} /><span>{props.canEditPlots ? t("sharedChanges") : t("readOnlyNote")}</span></div></aside>
    </> : <div className="desktop-page">{props.activeSection === "layers" ? <LayersPanel categories={props.categories} baseMap={props.baseMap} actions={props.actions} canManage={isAdmin} /> : null}{props.activeSection === "reports" ? <ReportsPanel plots={props.plots} categories={props.categories} actions={props.actions} /> : null}{props.activeSection === "history" ? <AuditPanel preview={props.preview} baseMap={props.baseMap} canRestore={isAdmin} onRestore={props.actions.restoreAuditEntry} workspace={props.workspace} /> : null}{props.activeSection === "users" ? <UsersPanel isAdmin={isAdmin} /> : null}{props.activeSection === "settings" ? <SettingsPanel actions={props.actions} canImport={isAdmin} plotStatuses={props.plotStatuses} workspace={props.workspace} testWorkspaceEnabled={props.testWorkspaceEnabled} canManageWorkspaces={isAdmin} canManageStatuses={isAdmin} /> : null}{props.activeSection === "profile" ? <ProfilePanel user={props.user} googleEnabled={props.googleEnabled} preview={props.preview} workspace={props.workspace} testWorkspaceEnabled={props.testWorkspaceEnabled} plotStatuses={props.plotStatuses} actions={props.actions} /> : null}</div>}
  </main>;
}
